version: '3'
services:

  sample:
    container_name: TransferBaseApp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development